WebSoft_RES/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from WebSoft_RES import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('', include('account.urls')),
    path('blog/', include('blog.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [

    path('login', views.UserLogin.as_view(), name='user_login'),
    path('logout', views.user_logout, name='user_logout'),
    path('register', views.UserRegister.as_view(), name='user_register')

    ]

blog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'blog'

urlpatterns = [
    path('detail/<slug:slug>', views.article_detail, name='blog_page'),
    path('list', views.article_list, name="blog_list"),
    path('topbar', views.TopbarPartialView.as_view(), name='topbar'),
    path('category/<int:pk>', views.category_detail, name="category_detail"),
]

home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
]

templates/includes/footer_link.html
{% load static %}
<div class="line"></div>
<footer>
    <div class="container">
        <div class="about">
            <h3>درباره وبسافت 3</h3>
            <p>وبسافت3 فعالیت خود را در تاریخ 1393/10/7 در زمینه تولید فیلم های آموزش طراحی سایت و و وردپرس آغاز کرده.
                یکی از دغدغه های بیشتر افراد محصل در رشته های مختلف و به خصوص رشته کامپیوتر، ترس از بیکاری و بدست
                نیاوردن شغل مورد علاقه شان بعد از فارغ التحصیلی هست. ما با در نظر گرفتن این موضوع و تلاش برای پوشش دادن
                این نوع دغدغه ها در حد توان به عنوان یک مرجع آموزشی سعی میکنیم</p>
        </div>

        <div class="f-menu">
            <h3>دسترسی 3</h3>
            <ul>
                <li><a href="#">پرداخت آنلاین</a></li>
                <li><a href="#">درباره ما</a></li>
                <li><a href="#">تماس با ما</a></li>
                <li><a href="#">همکاری با ما</a></li>
                <li><a href="#">خدمات ما</a></li>
            </ul>
        </div>

        <div class="f-menu">
            <h3>ارتباط با ما</h3>
            <ul>
                <li><i class="fas fa-mobile"></i>تلفن : 09353628781</li>
                <li><i class="fas fa-inbox"></i> ایمیل : websoft3.ir@gmail.com</li>
                <li>آدرس : تهران اصفهان مشهد</li>
            </ul>
        </div>
    </div>

    <div class="copy-right">
        <div class="container">
            <p>تمامی حقوق و مطالب سایت برای وبسافت3 محفوظ می باشد و کپی برداری از مطالب رایگان باذکر منبع آزاد است.</p>
            <div class="social">
                <a href="#"><i class="fab fa-facebook"></i></a>
                <a href="#"><i class="fab fa-telegram"></i></a>
                <a href="#"><i class="fab fa-twitter"></i></a>
                <a href="#"><i class="fab fa-youtube"></i></a>
                <a href="#"><i class="fab fa-linkedin"></i></a>
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

templates/includes/head_link.html
{% load static %}
<meta charset="UTF-8">
<meta name="viewport"
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<title>websoft3</title>

<link rel="stylesheet" href="{% static "css/all.css" %}">
<link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
<link rel="stylesheet" href="{% static "css/owl.theme.default.min.css" %}">
<link rel="stylesheet" href="{% static "css/style.css" %}">
{#<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">#}

templates/includes/sidebar.html
{% load static %}
<div class="sidebar">
    <div class="single-widget">
        <h4>آخرین مقالات</h4>
        <ul>
            {% for article in recent_articles %}
            <li><a href="{% url 'blog:blog_page' article.slug %}">{{ article.title }}</a></li>
            {% endfor %}
        </ul>
    </div>

    <div class="single-widget">
        <h4>آخرین مطالب</h4>
        <ul>
            <li><a href="#">آموزش افزونه گرویتی فرم برای ساخت انواع فرم </a></li>
            <li><a href="#">آموزش افزونه گرویتی فرم برای ساخت انواع فرم </a></li>
            <li><a href="#">آموزش افزونه گرویتی فرم برای ساخت انواع فرم </a></li>
            <li><a href="#">آموزش افزونه گرویتی فرم برای ساخت انواع فرم </a></li>
            <li><a href="#">آموزش افزونه گرویتی فرم برای ساخت انواع فرم </a></li>
            <li><a href="#">آموزش افزونه گرویتی فرم برای ساخت انواع فرم </a></li>
            <li><a href="#">آموزش افزونه گرویتی فرم برای ساخت انواع فرم </a></li>
            <li><a href="#">آموزش افزونه گرویتی فرم برای ساخت انواع فرم </a></li>
            <li><a href="#">آموزش افزونه گرویتی فرم برای ساخت انواع فرم </a></li>
            <li><a href="#">آموزش افزونه گرویتی فرم برای ساخت انواع فرم </a></li>
        </ul>
    </div>
</div>

templates/includes/top_bar.html
{% load static %}
<div class="top-menu">
    <div class="container">
        <div class="topbar-right">
            <ul>
                <li><i class="fas fa-phone"></i>مشاوره و پشتیبانی واتساپ:25665523</li>
                <li><i class="fa-regular fa-envelope"></i>ایمیل:websoft3.ir@gmail.com</li>
            </ul>
        </div>

        <div class="topbar-left">
            <ul>
                <li><i class="fas fa-search"></i></li>
                <li><i class="fas fa-shopping-bag"></i></li>
            </ul>
        </div>
    </div>
</div>

<header class="header">
    <div class="container">
        <div class="logo">
            <img alt="img/logo.jpg" src="{% static "img/logo.jpg" %}">
        </div>
        <nav class="main-menu">
            <ul>
                <li><a href="{% url 'home:home' %}">خانه</a></li>
                <li><a href="{% url 'blog:blog_list' %}">مقالات<i class="fas fa-angle-down"></i></a>
                    <ul>
                        {% for category in category %}
                            <li><a href="{% url 'blog:category_detail' category.id %}">{{ category.title }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li><a href="#">دوره ها</a></li>
                <li><a href="#">خدمات ما</a></li>
                {% if request.user.is_authenticated %}
                    <li><a href="#"><h3
                            style="font-family: 'Fedra Arabic Display AR+LT Black',serif">{{ request.user.fullname }}</h3>
                        <i class="fas fa-angle-down"></i></a>
                        <ul>
                            <li><a href="#">پروفایل</a></li>
                            <li><a href="{% url 'account:user_logout' %}">خروج از حساب</a></li>
                        </ul>
                    </li>
                    </ul>

                    </nav>

                {% else %}
                    <div class="sign">
                        <a href="{% url 'account:user_login' %}"><i class="fas fa-user-lock"></i>ورود/ثبت نام</a>
                    </div>
                {% endif %}
    </div>
</header>